frequency: 30.0
sensor_timeout: 1.0

odom0: /odom
odom0_config: [false, false, false, true, true, false]
odom0_queue_size: 10

imu0: /bno055/imu
imu0_config: [false, false, false, true, true, true]
imu0_differential: false
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: true
imu0_nodelay: true
imu0_frame_id: imu_link
